version: '3.8'

networks:
    app: ~

services:
    app:
        build: .
        volumes:
            - .:/srv/app
            - ./docker/app/php.ini:/usr/local/etc/php/php.ini
        networks:
            - app
        extra_hosts:
            - hostdocker.internal:host-gateway
        depends_on:
            - db

    nginx:
        image: nginx:alpine
        ports:
            - ${APP_PORT:-80}:80
        volumes:
            - .:/srv/app
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
        networks:
            - app
        depends_on:
            - app

    db:
        image: postgres:14-alpine
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./docker/volumes/db:/var/lib/postgresql/data
        networks:
            - app

    # db:
    #     image: mysql:5.7
    #     environment: 
    #         MYSQL_DATABASE: ${DB_DATABASE}
    #         MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    #         MYSQL_PASSWORD: ${DB_PASSWORD}
    #         MYSQL_USER: ${DB_USERNAME}
    #     volumes: 
    #         - ./docker/volumes/db:/var/lib/mysql
    #     networks:
    #         - app