version: '3.8'

services:
    app:
        build: .
        volumes:
            - .:/srv/app
            - ./docker/app/php.ini:/usr/local/etc/php/php.ini
        networks:
            - default
        extra_hosts:
            - host.docker.internal:host-gateway
        depends_on:
            - db

    nginx:
        image: nginx:alpine
        ports:
            - ${APP_PORT:-80}:80
        volumes:
            - .:/srv/app
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
        networks:
            - default
        depends_on:
            - app

    db:
        image: postgres:alpine
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./docker/volumes/db:/var/lib/postgresql/data
        networks:
            - default
    # db:
    #     image: mysql
    #     environment: 
    #         MYSQL_DATABASE: ${DB_DATABASE}
    #         MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    #         MYSQL_PASSWORD: ${DB_PASSWORD}
    #         MYSQL_USER: ${DB_USERNAME}
    #     volumes: 
    #         - ./docker/volumes/db:/var/lib/mysql
    #     networks:
    #         - default

    adminer:
        image: adminer
        ports:
            - ${ADMINER_PORT:-8002}:8080
        depends_on:
            - db
        networks:
            - default
    # phpmyadmin:
    #     image: phpmyadmin
    #     ports:
    #         - ${PHPMYADMIN_PORT:-8002}:80
    #     environment:
    #         PMA_HOST: db
    #         PMA_USER: ${DB_USERNAME}
    #         PMA_PASSWORD: ${DB_PASSWORD}
    #     depends_on:
    #         - db
    #     networks:
    #         - default

    mailpit:
        image: 'axllent/mailpit'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - default
